// Build src/knowledge/wikidata-foods.json from Wikidata (CC0): npm run build:dict
// Foods, dishes, drinks and fish/seafood species that have both a Japanese and a Chinese
// label. Simplified-only labels are converted to Taiwanese traditional with OpenCC.
import { writeFileSync } from "node:fs";
import * as OpenCC from "opencc-js";

const UA = { "user-agent": "japan-trip-bot/1.0 (github.com/KJLavender/japan-trip-bot)", accept: "application/sparql-results+json" };
const toTw = OpenCC.Converter({ from: "cn", to: "twp" });
const LANG_RANK: Record<string, number> = { "zh-tw": 0, "zh-hant": 1, "zh-hk": 2, zh: 3 };

const LABELS = `?item rdfs:label ?ja . FILTER(LANG(?ja) = "ja")
  ?item rdfs:label ?zh . FILTER(LANG(?zh) IN ("zh-tw","zh-hant","zh-hk","zh"))
  OPTIONAL { ?item skos:altLabel ?alt . FILTER(LANG(?alt) = "ja") }`;

const queries: [string, string][] = [];
// Food-ish classes, a couple of hops deep (deeper transitive queries time out).
for (const root of ["Q746549", "Q40050", "Q2095", "Q10675206", "Q2920963", "Q154", "Q192874"]) {
  for (const path of ["wdt:P31", "wdt:P279", "wdt:P31/wdt:P279", "wdt:P279/wdt:P279"]) {
    queries.push([`${root} ${path}`, `SELECT ?item ?ja ?zh ?alt WHERE { ?item ${path} wd:${root} . ${LABELS} }`]);
  }
}
// Species seen on izakaya/sushi menus: ray-finned fish, molluscs, crustaceans.
for (const taxon of ["Q127282", "Q25326", "Q25364"]) {
  queries.push([`taxon ${taxon}`, `SELECT ?item ?ja ?zh ?alt WHERE { ?item wdt:P171* wd:${taxon} . ?item wdt:P105 wd:Q7432 . ${LABELS} } LIMIT 30000`]);
}

interface Entry { ja: string[]; zh: string; lang: string; fish: boolean }
const byItem = new Map<string, Entry>();

for (const [name, q] of queries) {
  const res = await fetch("https://query.wikidata.org/sparql?format=json&query=" + encodeURIComponent(q), { headers: UA });
  if (!res.ok) {
    console.warn(`skip ${name}: HTTP ${res.status}`);
    continue;
  }
  const rows = (await res.json()).results.bindings as Record<string, { value: string; "xml:lang"?: string }>[];
  for (const r of rows) {
    const id = r.item.value.split("/").pop()!;
    const lang = r.zh["xml:lang"]!;
    const e = byItem.get(id) ?? { ja: [], zh: "", lang: "zz", fish: name.startsWith("taxon") };
    for (const j of [r.ja.value, r.alt?.value]) if (j && !e.ja.includes(j)) e.ja.push(j);
    if ((LANG_RANK[lang] ?? 9) < (LANG_RANK[e.lang] ?? 9)) [e.zh, e.lang] = [r.zh.value, lang];
    byItem.set(id, e);
  }
  console.log(`${name}: ${rows.length} rows`);
  await new Promise((r) => setTimeout(r, 1500)); // be polite to the query service
}

const KANA_ONLY = /^[぀-ゟ゠-ヿー]+$/;
const HIRAGANA_ONLY = /^[぀-ゟー]+$/;
const clean = (s: string) => s.replace(/[（(].*?[)）]/g, "").trim();
const usable = (ja: string) =>
  ja.length >= 2 && ja.length <= 20 && /[぀-ヿ一-鿿]/.test(ja) && !(HIRAGANA_ONLY.test(ja) && ja.length < 3);

const out: { ja: string[]; zh: string; fish?: true }[] = [];
for (const e of byItem.values()) {
  const zh = clean(e.lang === "zh" ? toTw(e.zh) : e.zh);
  const ja = [...new Set(e.ja.map(clean))].filter(usable);
  // Same text in both languages carries no information (豆腐→豆腐).
  if (!zh || ja.length === 0 || ja.every((j) => j === zh)) continue;
  out.push({ ja, zh, ...(e.fish ? { fish: true as const } : {}) });
}
out.sort((a, b) => a.ja[0].localeCompare(b.ja[0], "ja"));
writeFileSync(
  "src/knowledge/wikidata-foods.json",
  JSON.stringify({ source: "Wikidata (CC0) — generated by scripts/build-wikidata-dict.ts", generated: new Date().toISOString().slice(0, 10), entries: out }) + "\n",
);
console.log(`✅ ${out.length} entries (${out.filter((e) => e.fish).length} species), kana-only: ${out.filter((e) => e.ja.some((j) => KANA_ONLY.test(j))).length}`);
